name: flutter_dash
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  google_fonts: ^0.3.9
  text_to_path_maker: ^0.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Prata
      fonts:
        - asset: assets/fonts/Prata-Regular.ttf

    - family: Apple
      fonts:
        - asset: assets/fonts/HomemadeApple-Regular.ttf

    - family: Cabin
      fonts:
        - asset: assets/fonts/CabinSketch-Regular.ttf

    - family: Dot
      fonts:
        - asset: assets/fonts/RalewayDots-Regular.ttf

    - family: Elite
      fonts:
        - asset: assets/fonts/SpecialElite-Regular.ttf